import Head from 'next/head'
import Image from 'next/image'
import LoadingIndicator from "../components/LoadingIndicator";

import style9 from 'style9';

const styles = style9.create({
  container: {
    minHeight: '100vh',
    paddingLeft: '.5rem',
    paddingRight: '.5rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  },
  title: {
    fontSize: '24px',
  }
});

export default function Home() {
  return (
    <div className={style9(styles.container)}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={style9(styles.title)}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      <LoadingIndicator />
    </div>
  )
}
